const helpGroups = [
  { title: 'Ordering guide', items: [['How do I browse the menu?', 'Explore the full selection of drinks, cakes, meals, and handcrafted treats from the Menu tab.'], ['Can I customize a product?', 'Yes. Select the available size, add-ons, sugar level, temperature, and special instructions before adding an item to your cart.'], ['How do I place an order?', 'Review your cart, proceed to checkout, then confirm your delivery or pickup details and payment method.']] },
  { title: 'Delivery guide', items: [['What information is required for delivery?', 'Choose delivery at checkout and provide a complete address, contact number, and delivery instructions.'], ['How is the delivery fee calculated?', 'Standard rates apply based on your distance from the North Fairview branch. The final fee is shown during checkout.'], ['Where can I track my delivery?', 'Open My Orders and select Track order to view the latest order status.']] },
  { title: 'Pickup guide', items: [['How does store pickup work?', 'Choose Store pickup during checkout and collect your order from the North Fairview branch.'], ['When should I arrive?', 'Please arrive within your selected pickup window to help us serve your order at peak freshness.'], ['What should I show the barista?', 'Provide your order number to the barista when you arrive.']] },
  { title: 'Payment guide', items: [['Which digital payments are accepted?', 'The available methods are shown according to your fulfillment choice.'], ['How should I submit proof of payment?', 'When proof is required, upload a clear screenshot showing the transaction details and reference number.'], ['Should I keep my payment reference?', 'Yes. Keep your transaction reference number available for payment or order inquiries.']] },
  { title: 'Common questions', items: [['Can I modify my order?', 'Once an order is confirmed, modifications are limited. Contact support immediately so the team can check its current preparation status.'], ['How long does payment validation take?', 'The store team usually verifies submitted digital payments within 5–15 minutes.']] },
  { title: 'Cancellations and refunds', items: [['When can I request cancellation?', 'You may request cancellation before or during the preparation stage. Requests are reviewed by staff before approval.'], ['What happens to an unpaid order?', 'An unpaid order may be cancelled immediately and will be marked as Cancelled.'], ['What happens if the order is already paid?', 'Paid orders require approval before cancellation and may proceed to refund processing.'], ['How can I track a refund?', 'The order details may show the refund as Pending or Refunded. You will be notified when its status changes.'], ['Will a cancelled order disappear?', 'No. Cancelled orders remain visible in My Orders with their details for reference.']] },
]

export default function HelpPage() {
  return <main className="customer-main">
    <section className="page-hero help-hero"><span>Support center · North Fairview</span><h1>How can we help?</h1><p>Find quick answers about ordering, fulfillment, payments, cancellations, and refunds.</p></section>
    <section className="help-layout">
      <div className="faq-column"><div className="section-heading"><div><span className="eyebrow">Frequently asked questions</span><h2>Everything you need to order smoothly.</h2></div></div><div className="faq-groups">{helpGroups.map((group, groupIndex) => <section className="faq-group" key={group.title}><h3>{group.title}</h3>{group.items.map(([question, answer], itemIndex) => <details key={question} open={groupIndex === 0 && itemIndex === 0}><summary>{question}<span aria-hidden="true">+</span></summary><p>{answer}</p></details>)}</section>)}</div></div>
    </section>
  </main>
}
