import { AlertTriangle, ArrowUpRight, Boxes, PhilippinePeso, ShoppingBag, Users } from 'lucide-react'
import AppShell from '../components/AppShell'
import MetricCard from '../components/MetricCard'
import { inventory, orders } from '../data/mockData'
import StatusPill from '../components/StatusPill'

export default function AdminDashboard() {
  return <AppShell role="admin" eyebrow="Good afternoon, Admin! Here is what is happening at your cafe today." title="Dashboard" actions={<button className="button button-dark">Export Report</button>}><section className="metrics"><MetricCard label="Gross sales" value="₱384,290" detail="+8.2% this month" icon={PhilippinePeso}/><MetricCard label="Total orders" value="1,284" detail="+64 from last month" icon={ShoppingBag} tone="cream"/><MetricCard label="Active customers" value="892" detail="84 new this month" icon={Users} tone="blue"/><MetricCard label="Stock alerts" value="3" detail="Needs attention" icon={AlertTriangle} tone="rose"/></section><section className="dashboard-grid admin-grid"><article className="panel"><div className="panel-head"><div><span>Revenue trend</span><small>Last 7 days</small></div><select><option>This week</option></select></div><div className="line-chart"><div className="grid-lines"/><svg viewBox="0 0 600 180" preserveAspectRatio="none" aria-label="Revenue rising over seven days"><path d="M0 150 C70 145 80 105 145 115 S240 145 300 88 S390 52 450 72 S530 34 600 20" fill="none" stroke="#1b2f22" strokeWidth="4"/><path d="M0 150 C70 145 80 105 145 115 S240 145 300 88 S390 52 450 72 S530 34 600 20 L600 180 L0 180Z" fill="url(#fade)"/><defs><linearGradient id="fade" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#3a5c45" stopOpacity=".25"/><stop offset="1" stopColor="#3a5c45" stopOpacity="0"/></linearGradient></defs></svg><div className="chart-labels">{['Fri','Sat','Sun','Mon','Tue','Wed','Thu'].map(x=><span key={x}>{x}</span>)}</div></div></article><article className="panel inventory-panel"><div className="panel-head"><div><span>Inventory health</span><small>Live stock levels</small></div><Boxes size={19}/></div>{inventory.map(i=><div className="stock-row" key={i.name}><div><b>{i.name}</b><span>{i.stock} {i.unit}</span></div><div className="progress"><i style={{width:`${i.level}%`}} className={i.level<25?'low':''}/></div><small>{i.level}%</small></div>)}<button className="button button-soft">Open inventory <ArrowUpRight size={15}/></button></article></section><section className="panel"><div className="panel-head"><div><span>Latest transactions</span><small>Across online and in-store sales</small></div><button className="text-link dark">View all <ArrowUpRight size={15}/></button></div><div className="table-wrap"><table><thead><tr><th>Reference</th><th>Customer</th><th>Channel</th><th>Amount</th><th>Status</th></tr></thead><tbody>{orders.map(o=><tr key={o.id}><td><b>{o.id}</b></td><td>{o.customer}</td><td>{o.type}</td><td>₱{o.total}</td><td><StatusPill>{o.status}</StatusPill></td></tr>)}</tbody></table></div></section></AppShell>
}

