import { Download, Filter, Plus, Search, X } from 'lucide-react'
import { useMemo } from 'react'
import AppShell from '../components/AppShell'
import StatusPill from '../components/StatusPill'
import { useManagementSessionState } from '../hooks/useManagementSessionState'

const moduleConfigs={
 inventory:{role:'admin',title:'Inventory Monitoring',subtitle:'Track ingredient stock, thresholds, and recent deductions.',action:'Add Ingredient',columns:['Ingredient','Category','Current Stock','Reorder Level','Status'],rows:[['Espresso Beans','Coffee','8.4 kg','2 kg','Healthy'],['Fresh Milk','Dairy','9 L','5 L','Low Stock'],['Vanilla Syrup','Syrups','1.2 L','2 L','Low Stock']]},
 transactions:{role:'admin',title:'Transaction History',subtitle:'Review completed, pending, and cancelled transactions.',action:'Export',columns:['Order / ID','Type','Customer','Amount','Status'],rows:[['CR-1048','Delivery','Mika Santos','PHP 455.00','Preparing'],['CR-1047','Pickup','Aya Reyes','PHP 290.00','Ready'],['CR-1046','Walk-in','Noah Cruz','PHP 155.00','Completed']]},
 reports:{role:'admin',title:'Sales Report',subtitle:'Sales summaries by day, week, and month.',action:'Export Report',columns:['Period','Orders','Gross Sales','Discounts','Net Sales'],rows:[['Today','48','PHP 12,480.00','PHP 320.00','PHP 12,160.00'],['This Week','286','PHP 82,340.00','PHP 1,820.00','PHP 80,520.00']]},
 'inventory-report':{role:'admin',title:'Inventory Report',subtitle:'Ingredient movement, usage, and valuation.',action:'Export Report',columns:['Ingredient','Opening','Received','Used','Closing'],rows:[['Espresso Beans','10 kg','4 kg','5.6 kg','8.4 kg'],['Fresh Milk','14 L','12 L','17 L','9 L']]},
 cancellations:{role:'admin',title:'Cancellation Report',subtitle:'Monitor cancelled orders, reasons, and financial impact.',action:'Export Report',columns:['Order','Customer','Reason','Amount','Decision'],rows:[['CR-1039','Lia Tan','Customer request','PHP 310.00','Approved'],['CR-1028','Sam Yu','Item unavailable','PHP 185.00','Approved']]},
 products:{role:'admin',title:'Product Performance',subtitle:'Compare product sales, revenue, and contribution.',action:'Export',columns:['Product','Category','Qty Sold','Revenue','Performance'],rows:[['Iced Americano','Espresso','32','PHP 4,640.00','Best Seller'],['Espresso Blend','Espresso','27','PHP 4,185.00','Strong']]},
 trends:{role:'admin',title:'Sales Trends',subtitle:'Explore sales patterns and order demand over time.',action:'Export',columns:['Date','Walk-in','Pickup','Delivery','Total'],rows:[['Jul 23','PHP 4,820','PHP 3,150','PHP 4,510','PHP 12,480'],['Jul 22','PHP 4,340','PHP 2,980','PHP 3,760','PHP 11,080']]},
 team:{role:'admin',title:'User Management',subtitle:'Create and manage customer and internal accounts.',action:'Create Account',columns:['Name','Username','Role','Last Login','Status'],rows:[['Danica Reyes','danica.admin','Admin','Today, 1:42 PM','Active'],['Bea Cruz','bea.cashier','Cashier','Today, 8:02 AM','Active'],['Marco Lim','marco.staff','Operations Staff','Today, 7:55 AM','Active']]},
 settings:{role:'admin',title:'System Settings',subtitle:'Store information, schedules, orders, payments, branding, and security.',action:'Save Changes',columns:['Setting Group','Description','Last Updated','Owner','Status'],rows:[['Store Information','Address and contact details','Jul 20, 2026','Admin','Configured'],['Payment Settings','GCash and bank transfer','Jul 18, 2026','Admin','Configured'],['Login Protection','Attempts, sessions and OTP','Jul 14, 2026','Admin','Active']]},
 content:{role:'admin',title:'Content Management',subtitle:'Manage landing content, featured products, testimonials, and policies.',action:'Add Content',columns:['Content Block','Section','Published','Updated By','Status'],rows:[['Hero Banner','Landing','Yes','Admin','Published'],['Featured Menu','Menu Preview','Yes','Admin','Published'],['Delivery Policy','Policies','Yes','Admin','Published']]},
 logs:{role:'admin',title:'Activity Logs',subtitle:'Review administrative and internal account activity.',action:'Export Logs',columns:['Date & Time','Actor','Action','Module','Result'],rows:[['Jul 23, 1:42 PM','Admin','Updated store hours','System Settings','Success'],['Jul 23, 12:18 PM','Bea Cruz','Completed CR-1046','Cashier','Success']]},
 'staff-inventory':{role:'staff',title:'Inventory Management',subtitle:'Record stock activity and monitor ingredient availability.',action:'Record Activity',columns:['Ingredient','Category','Stock','Unit','Status'],rows:[['Espresso Beans','Coffee','8.4','kg','Healthy'],['Fresh Milk','Dairy','9','L','Low Stock'],['Vanilla Syrup','Syrups','1.2','L','Low Stock']]},
 menu:{role:'staff',title:'Manage Menu',subtitle:'Manage categories, products, availability, and recipes.',action:'Add New Item',columns:['Menu Item','Category','Price','Availability','Status'],rows:[['Espresso Blend','Espresso','PHP 155.00','In Stock','Active'],['Iced Americano','Espresso','PHP 145.00','In Stock','Active'],['Machiato','Espresso','PHP 170.00','In Stock','Active']]},
 'staff-transactions':{role:'staff',title:'Transactions',subtitle:'Review branch order and payment records.',action:'Export',columns:['Order','Customer','Type','Total','Status'],rows:[['CR-1048','Mika Santos','Delivery','PHP 455.00','Preparing'],['CR-1047','Aya Reyes','Pickup','PHP 290.00','Ready']]},
 preparation:{role:'staff',title:'Order Preparation',subtitle:'Prepare active orders and advance fulfillment status.',action:'Refresh Queue',columns:['Order','Placed','Customer','Items','Status'],rows:[['CR-1048','10:24 AM','Mika Santos','3 items','Preparing'],['CR-1047','10:17 AM','Aya Reyes','2 items','Ready'],['CR-1045','9:52 AM','Lia Tan','4 items','Pending']]},
}

export default function InternalModulePage({type}){
 const config=moduleConfigs[type]; const [query,setQuery]=useManagementSessionState(`${config.role}:${type}:query`,''); const [status,setStatus]=useManagementSessionState(`${config.role}:${type}:status`,'All'); const [modal,setModal]=useManagementSessionState(`${config.role}:${type}:modal`,false); const [recordName,setRecordName,clearRecordName]=useManagementSessionState(`${config.role}:${type}:record-name`,''); const [notes,setNotes,clearNotes]=useManagementSessionState(`${config.role}:${type}:notes`,'')
 const rows=useMemo(()=>config.rows.filter(row=>(status==='All'||row[row.length-1]===status)&&row.join(' ').toLowerCase().includes(query.toLowerCase())),[config,query,status])
 const action=()=>config.action.toLowerCase().includes('export')?alert(`${config.title} export is ready for Supabase data.`):setModal(true)
 return <AppShell role={config.role} title={config.title} eyebrow={config.subtitle} actions={<button className="legacy-primary" onClick={action}>{config.action.toLowerCase().includes('export')?<Download size={16}/>:<Plus size={16}/>} {config.action}</button>}>
  <section className="module-toolbar"><label><Search size={18}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={`Search ${config.title.toLowerCase()}`}/></label><div><Filter size={17}/>{['All','Active','Healthy','Low Stock','Pending','Preparing','Ready','Completed'].map(item=><button className={status===item?'active':''} onClick={()=>setStatus(item)} key={item}>{item}</button>)}</div></section>
  <section className="module-table-card"><div className="module-table-title"><div><h2>{config.title}</h2><span>{rows.length} record{rows.length===1?'':'s'}</span></div></div><div className="table-wrap"><table><thead><tr>{config.columns.map(column=><th key={column}>{column}</th>)}<th>Actions</th></tr></thead><tbody>{rows.map((row,index)=><tr key={`${row[0]}-${index}`}>{row.map((cell,cellIndex)=><td key={cellIndex}>{cellIndex===row.length-1?<StatusPill>{cell}</StatusPill>:cell}</td>)}<td><button className="module-action" onClick={()=>setModal(true)}>View</button></td></tr>)}</tbody></table>{!rows.length&&<div className="module-empty">No records match the selected filters.</div>}</div></section>
  {modal&&<div className="module-modal-backdrop" onMouseDown={()=>setModal(false)}><div className="module-modal" onMouseDown={e=>e.stopPropagation()} role="dialog" aria-modal="true"><header><div><span className="eyebrow">{config.role} module</span><h2>{config.action}</h2></div><button onClick={()=>setModal(false)} aria-label="Close"><X/></button></header><label>Record name<input value={recordName} onChange={e=>setRecordName(e.target.value)} placeholder="Enter a descriptive name"/></label><label>Notes<textarea rows="4" value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Add relevant details"/></label><footer><button className="legacy-ghost" onClick={()=>{clearRecordName();clearNotes();setModal(false)}}>Cancel</button><button className="legacy-primary" onClick={()=>{clearRecordName();clearNotes();setModal(false)}}>Save Record</button></footer></div></div>}
 </AppShell>
}
